# Generated by precisionFDA exporter (v1.0.3) on 2018-06-14 01:18:49 +0000
# The asset download links in this file are valid only for 24h.

# Exported app: clamms_normalize_coverage, revision: 12, authored by: evan.maxwell.2
# https://precision.fda.gov/apps/app-F0ZvBPQ0vZX31286X9jZKVVq

# For more information please consult the app export section in the precisionFDA docs

# Start with Ubuntu 14.04 base image
FROM ubuntu:14.04

# Install default precisionFDA Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	aria2 \
	byobu \
	cmake \
	cpanminus \
	curl \
	dstat \
	g++ \
	git \
	htop \
	libboost-all-dev \
	libcurl4-openssl-dev \
	libncurses5-dev \
	make \
	perl \
	pypy \
	python-dev \
	python-pip \
	r-base \
	ruby1.9.3 \
	wget \
	xz-utils

# Install default precisionFDA python packages
RUN pip install \
	requests==2.5.0 \
	futures==2.2.0 \
	setuptools==10.2

# Add DNAnexus repo to apt-get
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/amd64/' > /etc/apt/sources.list.d/dnanexus.list"
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/all/' >> /etc/apt/sources.list.d/dnanexus.list"
RUN curl https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg | apt-key add -

# Update apt-get
RUN DEBIAN_FRONTEND=noninteractive apt-get update

# Download app assets
RUN curl https://dl.dnanex.us/F/D/xX2YGfb0KgqkVfj5x19xgbvkX9j94ZfjKF1v42GP/clamms_normalize_coverage_assets.tar.gz | tar xzf - -C / --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/Z514B40BJ95X59v4VgJv9Fyb8JkgqKzYx2yV6p88/samtools-1.2.tar.gz | tar xzf - -C / --no-same-owner --no-same-permissions

# Download helper executables
RUN curl https://dl.dnanex.us/F/D/0K8P4zZvjq9vQ6qV0b6QqY1z2zvfZ0QKQP4gjBXp/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/bByKQvv1F7BFP3xXPgYXZPZjkXj9V684VPz8gb7p/run-1.2.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions

# Write app spec and code to root folder
RUN ["/bin/bash","-c","echo -E \\{\\\"spec\\\":\\{\\\"input_spec\\\":\\[\\{\\\"name\\\":\\\"bam_file\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Input\\ BAM\\ file\\\",\\\"help\\\":\\\"BAM\\ file\\\"\\},\\{\\\"name\\\":\\\"clamms_windows_bed_file\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"CLAMMS\\ windows\\ BED\\ file\\\",\\\"help\\\":\\\"BED\\ file\\ of\\ pre-computed\\ CLAMMS\\ windows\\\",\\\"default\\\":\\\"file-F0QK0k803q5pvvK5f0bG8ZFv\\\"\\},\\{\\\"name\\\":\\\"targets_bed_file\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Target\\ regions\\ BED\\ file\\\",\\\"help\\\":\\\"BED\\ file\\ of\\ target\\ regions\\ \\(e.g.\\ exons\\)\\\",\\\"default\\\":\\\"file-F0QJyPQ0V7B6Zj590J8YzqQ2\\\"\\}\\],\\\"output_spec\\\":\\[\\{\\\"name\\\":\\\"raw_coverage_bed_file\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Raw\\ \\(un-normalized\\)\\ coverage\\ file\\\",\\\"help\\\":\\\"Raw\\ read\\ coverage\\ summarized\\ over\\ CLAMMS\\ windows\\\"\\},\\{\\\"name\\\":\\\"normalized_coverage_bed_file\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Normalized\\ coverage\\ file\\\",\\\"help\\\":\\\"Normalized\\ read\\ coverage\\ summarized\\ over\\ CLAMMS\\ windows\\\"\\}\\],\\\"internet_access\\\":false,\\\"instance_type\\\":\\\"baseline-2\\\"\\},\\\"assets\\\":\\[\\\"file-F0KGb400V7B41y6xk1837B4y\\\",\\\"file-Bk5K6000qVb2Z7Q7qVJGZq5z\\\"\\],\\\"packages\\\":\\[\\]\\} \u003e /spec.json"]
RUN ["/bin/bash","-c","echo -E \\{\\\"code\\\":\\\"samtools\\ depth\\ -b\\ \\\\\\\"\\$targets_bed_file_path\\\\\\\"\\ -q\\ 0\\ -Q\\ 30\\ \\\\\\\"\\$bam_file_path\\\\\\\"\\ \\\\u003e\\ \\\\\\\"\\$\\{bam_file_prefix\\}.depth.txt\\\\\\\"\\\\n\\\\nsam_gatk_coverage_to_bed\\ \\\\\\\"\\$\\{bam_file_prefix\\}.depth.txt\\\\\\\"\\ \\\\\\\"\\$clamms_windows_bed_file_path\\\\\\\"\\ \\\\u003e\\ \\\\\\\"\\$\\{bam_file_prefix\\}.raw.coverage.bed\\\\\\\"\\\\n\\\\nnormalize_coverage\\ \\\\\\\"\\$\\{bam_file_prefix\\}.raw.coverage.bed\\\\\\\"\\ \\\\\\\"\\$clamms_windows_bed_file_path\\\\\\\"\\ \\\\u003e\\ \\\\\\\"\\$\\{bam_file_prefix\\}.normalized.coverage.bed\\\\\\\"\\\\n\\\\nemit\\ raw_coverage_bed_file\\ \\\\\\\"\\$\\{bam_file_prefix\\}.raw.coverage.bed\\\\\\\"\\\\nemit\\ normalized_coverage_bed_file\\ \\\\\\\"\\$\\{bam_file_prefix\\}.normalized.coverage.bed\\\\\\\"\\\"\\} | python -c 'import sys,json; print json.load(sys.stdin)[\"code\"]' \u003e /script.sh"]

# Create directory /work and set it to $HOME and CWD
RUN mkdir -p /work
ENV HOME="/work"
WORKDIR /work

# Set entry point to container
ENTRYPOINT ["/usr/bin/run"]

VOLUME /data
VOLUME /work